export const carBrands = [
  {
    name: 'Mercedes-Benz',
    children: [
      '124',
      '1317',
      '170',
      '1722',
      '180',
      '190',
      '1920',
      '200',
      '208',
      '209D',
      '210/310',
      '220',
      '230',
      '240',
      '250',
      '2533',
      '260',
      '270',
      '280',
      '290',
      '300',
      '308',
      '320',
      '350',
      '380',
      '400',
      '416',
      '420',
      '450',
      '500',
      '560',
      '600',
      '609D',
      '814',
      '814D',
      'A-Class',
      'A 140',
      'A 150',
      'A 160',
      'A 170',
      'A 180',
      'A 190',
      'A 200',
      'A 210',
      'A 220',
      'A 250',
      'A 35',
      'A 35 AMG',
      'A 45 AMG',
      'Accelo',
      'Actros',
      'AMG GT',
      'Antos',
      'Arocs',
      'Atego',
      'Axor',
      'B-Class',
      'B 150',
      'B 160',
      'B 170',
      'B 180',
      'B 200',
      'B 220',
      'B 250',
      'B Electric Drive',
      'C-Class',
      'C 160',
      'C 180',
      'C 200',
      'C 220',
      'C 230',
      'C 240',
      'C 250',
      'C 270',
      'C 280',
      'C 30 AMG',
      'C 300',
      'C 32 AMG',
      'C 320',
      'C 350',
      'C 36 AMG',
      'C 400',
      'C 43 AMG',
      'C 450',
      'C 55 AMG',
      'C 63 AMG',
      'Capa',
      'CE-Class',
      'CE 200',
      'CE 220',
      'CE 230',
      'CE 240',
      'CE 280',
      'CE 300',
      'CE 320',
      'Citaro',
      'CL-Class',
      'CL 160',
      'CL 180',
      'CL 200',
      'CL 220',
      'CL 230',
      'CL 420',
      'CL 500',
      'CL 55 AMG',
      'CL 600',
      'CL 63 AMG',
      'CL 65 AMG',
      'CLA-Class',
      'CLA 180',
      'CLA 200',
      'CLA 220',
      'CLA 250',
      'CLA 45 AMG',
      'CLC-Class',
      'CLC 180',
      'CLC 200',
      'CLC 230',
      'CLC 350',
      'CLE-Class',
      'CLE  220',
      'CLE 200',
      'CLE 220d',
      'CLE 300',
      'CLE 450',
      'CLE 53 AMG',
      'CLK-Class',
      'CLK 200',
      'CLK 220',
      'CLK 230',
      'CLK 240',
      'CLK 270',
      'CLK 280',
      'CLK 320',
      'CLK 350',
      'CLK 430',
      'CLK 500',
      'CLK 55 AMG',
      'CLK 65 AMG',
      'CLS-Class',
      'CLS 220',
      'CLS 250',
      'CLS 280',
      'CLS 300',
      'CLS 320',
      'CLS 350',
      'CLS 400',
      'CLS 450',
      'CLS 500',
      'CLS 55 AMG',
      'CLS 63 AMG',
      'Conecto',
      'E-Class',
      'E 200',
      'E 220',
      'E 230',
      'E 240',
      'E 250',
      'E 260',
      'E 270',
      'E 280',
      'E 290',
      'E 300',
      'E 320',
      'E 350',
      'E 36 AMG',
      'E 380',
      'E 400',
      'E 416',
      'E 420',
      'E 43 AMG',
      'E 430',
      'E 450',
      'E 50',
      'E 50 AMG',
      'E 500',
      'E 53 AMG',
      'E 55',
      'E 55 AMG',
      'E 560',
      'E 60 AMG',
      'E 63 AMG',
      'E550',
      'Econic',
      'EQA',
      'EQB',
      'EQC',
      'EQE',
      'EQE 53 AMG',
      'EQE SUV',
      'EQE SUV AMG',
      'EQG',
      'EQS',
      'EQS SUV',
      'EQV',
      'G-Class',
      'G 230',
      'G 240',
      'G 250',
      'G 270',
      'G 280',
      'G 290',
      'G 300',
      'G 320',
      'G 350',
      'G 400',
      'G 500',
      'G 55 AMG',
      'G 550',
      'G 580',
      'G 63 AMG',
      'GL-Class',
      'GL 320',
      'GL 350',
      'GL 400',
      'GL 420',
      'GL 450',
      'GL 500',
      'GL 55 AMG',
      'GL 550',
      'GL 63 AMG',
      'GLA-Class',
      'GLA 180',
      'GLA 200',
      'GLA 220',
      'GLA 250',
      'GLA 35 AMG',
      'GLA 45 AMG',
      'GLB 250',
      'GLC-Class',
      'GLC 200',
      'GLC 220',
      'GLC 250',
      'GLC 300',
      'GLC 350',
      'GLC 400',
      'GLC 43 AMG',
      'GLC 63',
      'GLE-Class',
      'GLE 250',
      'GLE 300',
      'GLE 350',
      'GLE 400',
      'GLE 43 AMG',
      'GLE 450',
      'GLE 500',
      'GLE 53 AMG',
      'GLE 53 AMG Coupe',
      'GLE 63 AMG',
      'GLE 63 S Coupe',
      'GLK-Class',
      'GLK 200',
      'GLK 220',
      'GLK 250',
      'GLK 280',
      'GLK 300',
      'GLK 320',
      'GLK 350',
      'GLS-Class',
      'GLS 350',
      'GLS 400',
      'GLS 450',
      'GLS 500',
      'GLS 600 Maybach',
      'GLS 63 AMG',
      'Integro',
      'Intouro',
      'MB 100',
      'ML-Class',
      'ML 230',
      'ML 250',
      'ML 270',
      'ML 280',
      'ML 300',
      'ML 320',
      'ML 350',
      'ML 400',
      'ML 420',
      'ML 430',
      'ML 450',
      'ML 500',
      'ML 55 AMG',
      'ML 63 AMG',
      'R-Class',
      'R 280',
      'R 300',
      'R 320',
      'R 350',
      'R 500',
      'R 63 AMG',
      'S-Class',
      'S 250',
      'S 260',
      'S 280',
      'S 300',
      'S 320',
      'S 350',
      'S 400',
      'S 420',
      'S 430',
      'S 450',
      'S 500',
      'S 500 Coupe',
      'S 55  AMG',
      'S 550',
      'S 560',
      'S 580',
      'S 580 Maybach',
      'S 600',
      'S 600 Coupe',
      'S 63 AMG',
      'S 63 AMG Coupe',
      'S 65 AMG',
      'S 65 AMG Coupe',
      'S 680 Maybach 4MATIC',
      'SL 420',
      'SL-Class',
      'SL 230',
      'SL 250',
      'SL 280',
      'SL 300',
      'SL 320',
      'SL 350',
      'SL 380',
      'SL 400',
      'SL 450',
      'SL 500',
      'SL 55 AMG',
      'SL 560',
      'SL 60 AMG',
      'SL 600',
      'SL 63 AMG',
      'SL 65 AMG',
      'SL 70 AMG',
      'SL 73 AMG',
      'SLC-Class',
      'SLC 180',
      'SLC 200',
      'SLC 250',
      'SLC 300',
      'SLC 43 AMG',
      'SLK-Class',
      'SLK 200',
      'SLK 230',
      'SLK 250',
      'SLK 280',
      'SLK 300',
      'SLK 32 AMG',
      'SLK 320',
      'SLK 350',
      'SLK 55 AMG',
      'SLR McLaren',
      'SLS-Class',
      'SLS 63 AMG',
      'SLS 63 AMG Cabrio',
      'Smart',
      'Sprinter',
      'T-Class',
      'T 160',
      'T 180',
      'Tourino',
      'Transporter',
      'Travego',
      'Turismo',
      'Unimog',
      'V-Class',
      'V 200',
      'V 220',
      'V 230',
      'V 250',
      'V 280',
      'V 300',
      'V 350',
      'Vaneo',
      'Vario',
      'Viano',
      'Vito',
      'X-Class',
      'x220d',
      'x250d',
      'Zetros',
    ],
  },
  {
    name: 'Toyota',
    children: [
      '4-Runner',
      'Allex',
      'Alphard',
      'Altezza',
      'Aristo',
      'Aurion',
      'Auris',
      'Avalon',
      'Avensis',
      'Aygo',
      'BB',
      'Belta',
      'Blade',
      'Brevis',
      'Bz3',
      'BZ3X',
      'Bz4X',
      'C-HR',
      'Caldina',
      'Camry',
      'Carina',
      'Celica',
      'Celsior',
      'Century',
      'Chaser',
      'Coaster',
      'Corolla',
      'Corolla Cross',
      'Corona',
      'Cressida',
      'Cresta',
      'Crown',
      'Curren',
      'Duet',
      'Dyna',
      'Estima',
      'FJ Cruiser',
      'Fortuner',
      'Funcargo',
      'Gaia',
      'GR',
      'Grand Hiace',
      'GT86',
      'Harrier',
      'Hiace',
      'Highlander',
      'Hilux',
      'Ipsum',
      'iQ',
      'Isis',
      'Ist',
      'Izoa',
      'Kluger',
      'Land Cruiser 100',
      'Land Cruiser 200',
      'Land Cruiser 300',
      'Land Cruiser 70',
      'Land Cruiser 80',
      'Land Cruiser Prado',
      'Lite-Ace',
      'Mark 2',
      'Mark X (10)',
      'Mark X ZiO',
      'Matrix',
      'Mirai',
      'MR 2',
      'MR-S',
      'Nadia',
      'Noah',
      'Opa',
      'Optimo',
      'Paseo',
      'Passo',
      'Picnic',
      'Platz',
      'Previa',
      'Prius',
      'Probox',
      'Progres',
      'Raize',
      'Raum',
      'Rav 4',
      'Rush',
      'Sequoia',
      'Sienna',
      'Sienta',
      'Soarer',
      'Solara',
      'Starlet',
      'Supra',
      'Tacoma',
      'Tercel',
      'Town Ace',
      'Toyoace',
      'Tundra',
      'Venza',
      'Verossa',
      'Vista',
      'Vista Ardeo',
      'Vitz',
      'Voxy',
      'WILL',
      'Windom',
      'Wish',
      'Yaris',
    ],
  },
  {
    name: 'Nissan',
    children: [
      '370 Z',
      '180 SX',
      '200 SX',
      '240 SX',
      '280 SX',
      '300 ZX',
      '350 Z',
      'AD',
      'Almera',
      'Almera Tino',
      'Altima',
      'Ariya',
      'Armada',
      'Atlas',
      'Avenir',
      'BAssara',
      'BlueBird',
      'Cabstar',
      'Cargo',
      'Cedric',
      'Cefiro',
      'Cherry',
      'Cima',
      'Civilian',
      'Crew',
      'Cube',
      'Datsun',
      'Dualis',
      'Elgrand',
      'Expert',
      'Fairlady',
      'Frontier',
      'Fuga',
      'Gloria',
      'GT-R',
      'Interstar',
      'Juke',
      'Kicks',
      'King Cab',
      'Kubistar',
      'Lafesta',
      'Largo',
      'Laurel',
      'Leaf',
      'Leopard',
      'Liberty',
      'March',
      'Maxima',
      'Maxima QX',
      'Micra',
      'Mistral',
      'Murano',
      'Navara',
      'Note',
      'NV200',
      'Pathfinder',
      'Patrol',
      'Pickup',
      'Prairie',
      'Presage',
      'Presea',
      'President',
      'Primera',
      'Primstar',
      'Pulsar',
      'Qashqai',
      'Quest',
      'Rasheen',
      'Rnessa',
      'Rogue',
      'Safari',
      'Sentra',
      'Serena',
      'Silvia',
      'Skyline',
      'Stagea',
      'Stanza',
      'Sunny',
      'Teana',
      'Terrano',
      'Terrano II',
      'Tiida',
      'Tino',
      'Titan',
      'Trade',
      'Urvan',
      'Vanette',
      'Versa',
      'Wingroad',
      'X-Trail',
      'Xterra',
    ],
  },
  {
    name: 'BMW',
    children: [
      'C 650 Sport',
      '1 Series',
      '114',
      '116',
      '118',
      '120',
      '123',
      '125',
      '130',
      '135',
      '140',
      '2 Series',
      '2002',
      '214',
      '216',
      '218',
      '220',
      '225',
      '228',
      '230',
      '235',
      '240',
      '3 Series',
      '315',
      '316',
      '318',
      '320',
      '323',
      '324',
      '325',
      '328',
      '330',
      '335',
      '340',
      'Active Hybrid 3',
      '4 Series',
      '418',
      '420',
      '425',
      '428',
      '430',
      '435',
      '440',
      '5 Series',
      '518',
      '520',
      '523',
      '524',
      '525',
      '528',
      '530',
      '535',
      '540',
      '545',
      '550',
      'Active Hybrid 5',
      '6 Series',
      '628',
      '630',
      '633',
      '635',
      '640',
      '645',
      '650',
      '7 Series',
      '725',
      '728',
      '730',
      '732',
      '735',
      '740',
      '745',
      '750',
      '760',
      'Active Hybrid 7',
      '8 Series',
      '820',
      '840',
      '850',
      'C 650 GT',
      'C evolution',
      'F 700 GS',
      'F 800 GS',
      'F 800 GS Adventure',
      'F 800 GT',
      'F 800 R',
      'G 310 GS',
      'G 310 R',
      'G 650 GS',
      'i Series',
      'i3',
      'i4',
      'i5',
      'i7',
      'i8',
      'iX',
      'iX1',
      'iX3',
      'IX2',
      'K 1600 GT',
      'K 1600 GTL',
      'M Series',
      'M1',
      'M2',
      'M3',
      'M4',
      'M5',
      'M6',
      'M8',
      'R 1200 GS',
      'R 1200 R',
      'R 1200 RT',
      'R nineT',
      'R nineT Pure',
      'R nineT Racer',
      'R nineT Scrambler',
      'R nineT Urban G/S',
      'S 1000 R',
      'S 1000 RR',
      'S 1000 XR',
      'X Series',
      'X1',
      'X2',
      'X3',
      'X3 M',
      'X4',
      'X4 M',
      'X5',
      'X5 M',
      'X6',
      'X6 M',
      'X7',
      'XM',
      'Z Series',
      'Z1',
      'Z3',
      'Z4',
      'Z8',
    ],
  },
  {
    name: 'Hyundai',
    children: [
      'Accent',
      'Aero Town',
      'Atos',
      'Avante',
      'Azera',
      'Centennial',
      'County',
      'Coupe',
      'Creta',
      'Dynasty',
      'Elantra',
      'Encino',
      'Equus',
      'Excel',
      'Galloper',
      'Genesis',
      'Genesis Coupe',
      'Getz',
      'Gold',
      'Grandeur',
      'H 100',
      'H 200',
      'H-1',
      'HD',
      'HL',
      'HSL',
      'i10',
      'i20',
      'i30',
      'i30cw wagon',
      'i40 Sedan',
      'i40 Tourer',
      'i45',
      'Ioniq',
      'ix20',
      'ix35',
      'Kona',
      'Lantra',
      'Lavita',
      'Marcia',
      'Matrix',
      'NF',
      'Palisade',
      'Pony',
      'Porter',
      'Porter II',
      'Prime',
      'R210',
      'S Coupe',
      'Santa Cruz',
      'Santa Fe',
      'Santamo',
      'Solaris',
      'Sonata',
      'Sonica',
      'Starex',
      'Stelar',
      'Terracan',
      'Tiburon',
      'Trajet',
      'Tucson',
      'Veloster',
      'Venue',
      'Veracruz',
      'XG 30',
      'XG 350',
    ],
  },
  {
    name: 'Acura',
    children: [
      'CL',
      'EL',
      'ILX',
      'Integra',
      'Legend',
      'MDX',
      'NSX',
      'RDX',
      'RL',
      'RLX',
      'RSX',
      'SLX',
      'TL',
      'TLX',
      'TSX',
      'Vigor',
      'ZDX',
    ],
  },
  {
    name: 'Aiqar',
    children: ['03', 'Arrizo', 'Arrizo e', 'eQ1', 'eQ3', 'eQ7', 'QQ'],
  },
  {
    name: 'Aito',
    children: ['M5', 'M9'],
  },
  {
    name: 'Alfa Romeo',
    children: [
      '145',
      '146',
      '147',
      '155',
      '156',
      '159',
      '164',
      '166',
      '33',
      '75',
      '90',
      'Brera',
      'Crosswagon',
      'Giulia',
      'Giulietta',
      'GT',
      'GTV',
      'RZ/SZ',
      'Spider',
      'Sportwagon',
      'Sprint',
      'Stelvio',
    ],
  },
  {
    name: 'Alpina',
    children: ['B3', 'B4', 'B5', 'B6', 'B7', 'D3', 'D4', 'D5', 'XD3'],
  },
  {
    name: 'Arcfox',
    children: ['Alpha S', 'Alpha S5', 'Alpha T', 'Alpha T5', 'Kaola'],
  },
  {
    name: 'Aston Martin',
    children: [
      'AR 1',
      'DB',
      'DB11',
      'DB7',
      'DB8',
      'DB9',
      'DB9 GT',
      'DBX',
      'Lagonda Taraf',
      'Legonda',
      'Rapid',
      'Rapid S',
      'V 12 Vanguish',
      'V12 Vantage S',
      'V12 Vantage S Roadster',
      'V8',
      'V8 Vantage',
      'V8 Vantage S',
      'V8 Vantage S Roadster',
      'Vanguish',
      'Vanguish S',
      'Vanguish Volante',
      'Vanguish Zagato',
      'Vantage',
      'Vantage GT8',
      'Virage',
      'Vulcan',
    ],
  },
  {
    name: 'Audi',
    children: [
      '100',
      '200',
      '80',
      '90',
      'A1',
      'A2',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'A8',
      'Allroad',
      'Cabriolet',
      'Coupe',
      'e-tron',
      'e-tron GT',
      'Q2',
      'Q2L e-tron',
      'Q3',
      'Q4',
      'Q4 e-tron',
      'Q5',
      'Q5 e-tron',
      'Q7',
      'Q8',
      'Q8 e-tron',
      'R8',
      'RS e-tron',
      'RS2',
      'RS4',
      'RS5',
      'RS6',
      'RS7',
      'RSQ8',
      'S2',
      'S3',
      'S4',
      'S5',
      'S6',
      'S7',
      'S8/R8',
      'SQ5',
      'SQ8',
      'TT',
      'V8',
    ],
  },
  {
    name: 'Avatr',
    children: ['07', '11', '12'],
  },
  {
    name: 'Bentley',
    children: [
      'Arnage',
      'Azure',
      'Bentayga',
      'Brooklands',
      'Continental Flying Spur',
      'Continental GT',
      'Eight',
      'Flying Spur',
      'Mulsanne',
      'Turbo R',
      'Turbo RT',
      'Turbo S',
    ],
  },
  {
    name: 'Bugatti',
    children: ['Chiron', 'Veyron'],
  },
  {
    name: 'Buick',
    children: [
      'Apollo',
      'Century',
      'E4',
      'E5',
      'Electra Wagon',
      'Enclave',
      'Encore',
      'GL 8',
      'Le Sabre',
      'Lucerne',
      'Park Avenue',
      'Regal',
      'Rendez Vous',
      'Rivera',
      'Roadmaster',
      'Skylark',
      'Terraza',
      'Velite 6',
      'Velite 7',
      'Verano',
    ],
  },
  {
    name: 'BYD',
    children: [
      'Dolphin',
      'E2',
      'E5',
      'F0 GL-i',
      'F0 GLX-i',
      'F3 ATI',
      'F3 GL-i',
      'F3 GLX-i',
      'F3R AT',
      'F3R GLX-i',
      'F6',
      'G3 GLX-I',
      'Han EV',
      'Leopard 5',
      'Qin',
      'Qin L',
      'Qin Plus',
      'S6 GS-I',
      'Sea Lion 05',
      'SEA Lion 07',
      'Seagull',
      'Seal',
      'Seal 06 GT',
      'Song  L',
      'Song Plus',
      'Tang',
      'Yuan',
      'Yuan Plus',
      'Yuan Up',
    ],
  },
  {
    name: 'Cadillac',
    children: [
      'Allante',
      'ATS',
      'BLS',
      'Brougham',
      'Catera',
      'Cimarron',
      'CT4',
      'CT5',
      'CT6',
      'CTS',
      'De Ville',
      'DTS',
      'Eldorado',
      'ELR',
      'Escalade',
      'Fleetwood',
      'LaSalle',
      'Lyriq',
      'Seville',
      'SRX',
      'STS',
      'Vizon',
      'XLR',
      'XT4',
      'XT5',
      'XT6',
      'XTS',
    ],
  },
  {
    name: 'Changan',
    children: ['Deepal S7', 'E-Star', 'EM 60 EV', 'EM80', 'EV-460', 'UNI-K', 'Uni-T', 'Uni-V'],
  },
  {
    name: 'Chery',
    children: [
      'A21',
      'Arrizo 8',
      'B13',
      'B14',
      'EQ7',
      'Flagcloud',
      'Oriental Son',
      'QQ',
      'S16',
      'Tiggo7',
      'Tiggo8',
      'Tigo',
    ],
  },
  {
    name: 'Chevrolet',
    children: [
      'Alero',
      'Astro VAn',
      'Avalanche',
      'Aveo',
      'Baretta',
      'Blazer',
      'Bolt EV',
      'C1500',
      'C2500',
      'C3500',
      'Camaro',
      'Caprice',
      'Captiva',
      'Cavalier',
      'Celebrity',
      'Chevelle',
      'Chevy van',
      'Citation',
      'Cobalt',
      'Colorado',
      'Corsica',
      'Corvette',
      'Cruze',
      'El Camino',
      'Epica',
      'Equinox',
      'Evanda',
      'Express',
      'Geo Storm',
      'Groove',
      'HHR',
      'Impala',
      'K1500',
      'K2500',
      'K30',
      'K3500',
      'Kalos',
      'Labo',
      'Lacetti',
      'Lanos',
      'Lumina',
      'Malibu',
      'Matiz',
      'Menlo',
      'Metro',
      'Monte Carlo',
      'Niva',
      'Nova',
      'Nubira',
      'Onix',
      'Orlando',
      'Prizm',
      'Rezzo',
      'S-10',
      'Seeker',
      'Silver',
      'Silverado',
      'Sonic',
      'Spark',
      'Spectrum',
      'Sprint',
      'SS Sedan',
      'SSR',
      'Starcraft',
      'Suburban',
      'Tahoe',
      'Tracker',
      'Trailblazer',
      'Trans Sport',
      'Traverse',
      'Trax',
      'Uplander',
      'Van',
      'Van 20',
      'Venture',
      'Viva',
      'Volt',
      'Yukon',
      'Zafira',
    ],
  },
  {
    name: 'Chrysler',
    children: [
      '200',
      '300',
      '300 C',
      '300 M',
      'Crossfire',
      'Daytona',
      'ES',
      'Grand Voyager',
      'GS',
      'GTS',
      'Imperial',
      'Le Baron',
      'Neon',
      'New Yorker',
      'Pacifica',
      'Prowler',
      'PT Cruiser',
      'Ram Van',
      'Saratoga',
      'Sebring',
      'Smart',
      'Stratus',
      'Town & Country',
      'Valiant',
      'Viper',
      'Vision',
      'Voyager',
    ],
  },
  {
    name: 'Citroen',
    children: [
      '2 CV',
      'AX',
      'Berlingo',
      'BX',
      'C-Crosser',
      'C-Elysee',
      'C1',
      'C2',
      'C3',
      'C4',
      'C4 Picasso',
      'C5',
      'C6',
      'C8',
      'CX',
      'DS',
      'DS 3',
      'DS 4',
      'DS 4 Crossback',
      'DS 5',
      'Evasion',
      'Grand C4 Picasso',
      'GSA',
      'Jumper',
      'Jumpy',
      'Nouveau Jumpy',
      'Saxo',
      'Synergie',
      'Visa',
      'Xantia',
      'XM',
      'Xsara',
      'Xsara Picasso',
      'ZX',
    ],
  },
  {
    name: 'Daewoo',
    children: [
      'Assol',
      'Condr',
      'Damas',
      'Espero',
      'Evanda',
      'Kalos',
      'Korando',
      'Lacetti',
      'Lanos',
      'Leganza',
      'Lemans',
      'Magnus',
      'Matiz',
      'Nexia',
      'Novus',
      'Nubira',
      'Prince',
      'Racer',
      'Rezzo',
      'Super Salon',
      'Tacuma',
      'Tico',
      'Vanetti',
    ],
  },
  {
    name: 'Daihatsu',
    children: [
      'Altis',
      'Applause',
      'Atrai',
      'Charade',
      'Charmant',
      'Copen',
      'Coure',
      'Delta',
      'Extol',
      'Feroza',
      'Freeclimber',
      'Gran Move',
      'Hi Jet',
      'Hijet',
      'Leeza',
      'Max',
      'Mira',
      'Move',
      'Naked',
      'Opti',
      'Pizar',
      'Rocky',
      'Rugger',
      'Sirion',
      'Terios',
      'YRV',
    ],
  },
  {
    name: 'Denza',
    children: ['Denza D9', 'Denza N7', 'Denza N8', 'Denza Z9', 'Denza Z9 GT', 'N9'],
  },
  {
    name: 'DFSK',
    children: ['E5 Plus', 'EC31', 'EC35', 'EC75', 'EV200', 'EV400', 'Yufeng V9'],
  },
  {
    name: 'Dodge',
    children: [
      '1500',
      '2500',
      '3500',
      '600',
      'Aries',
      'Aspen',
      'Avenger',
      'Caliber',
      'Challenger',
      'Charger',
      'Cirrus',
      'Colt',
      'Dakota',
      'Dart',
      'Daytona',
      'Diplomat',
      'Durango',
      'Dynasty',
      'Grand Caravan',
      'Intrepid',
      'Journey',
      'Magnum',
      'Mirada',
      'Monaco',
      'Neon',
      'Nitro',
      'Omni',
      'RAM',
      'RAM 250',
      'Rider',
      'Shadow',
      'Spirit',
      'Sprinter',
      'Stealth',
      'Stratus',
      'Viper',
      'Այլ/Օther',
    ],
  },
  {
    name: 'Dongfeng',
    children: [
      '007',
      '008',
      'Box',
      'CHENGLONG BEV L2',
      'Chenglong M3',
      'E11 K',
      'EC31 Cargo Box (PVC)',
      'EC31 L',
      'EC31 S',
      'EC35 II',
      'EC35 V',
      'EC71 L',
      'EC71 L Cargo Box',
      'EC72',
      'EC75 EV Cargo Box',
      'ED71',
      'ED71 Cargo Box',
      'EG71',
      'ES50',
      'EX1',
      'Forthing Friday ev SUV',
      'Forthing S50 EV',
      'Forthing S60 EV',
      'Forthing T5',
      'Forthing T5EVO',
      'Forthing T5HEV',
      'M 5 EV',
      'Mengshi',
      'MNV',
      'Rich 6EV Pickup',
      'RICH6 Pickup',
      'S60',
      'S7',
      'SKY EV',
      'V9',
    ],
  },
  {
    name: 'Eagle',
    children: ['Medallion', 'Premier', 'Summit', 'Talon', 'Vision', 'Այլ/Օther'],
  },
  {
    name: 'ErAZ',
    children: ['3218', '3730', '762', 'Այլ/Օther'],
  },
  {
    name: 'Exeed',
    children: ['LX', 'RX', 'TXL', 'VX'],
  },
  {
    name: 'Fangchengbao',
    children: ['Leopard 3', 'Leopard 5', 'Leopard 8'],
  },
  {
    name: 'FAW',
    children: ['Besturn B50'],
  },
  {
    name: 'Ferrari',
    children: [
      '208',
      '246',
      '250',
      '275',
      '288',
      '296 GTB',
      '308',
      '328',
      '330',
      '348',
      '360 Modena',
      '365',
      '400',
      '412',
      '456 GT',
      '458 Italia',
      '512 M',
      '575',
      '599 GTB',
      '612',
      '612 Scaglietti',
      '750',
      'California',
      'Daytona',
      'Dino GT 4',
      'Enzo Ferrari',
      'F12',
      'F355',
      'F360',
      'F40',
      'F430',
      'F440',
      'F50',
      'F512',
      'F550',
      'F60',
      'F8',
      'FF',
      'FXX',
      'GTC4 Lusso',
      'LaFerrari',
      'Maranello',
      'Mondial',
      'Purosangue',
      'Scuderia Spider 16M',
      'SF90',
      'Superamerica',
      'Testarossa',
      'Այլ/Օther',
    ],
  },
  {
    name: 'Fiat',
    children: [
      '124',
      '126',
      '127',
      '128',
      '130',
      '131',
      '132',
      '500',
      'Argenta',
      'Barchetta',
      'Brava',
      'Bravo',
      'Cinquecento',
      'Coupe',
      'Croma',
      'Dino',
      'Doblo',
      'Ducato',
      'Fiorino',
      'Grande Punto',
      'Idea',
      'Lancia',
      'Linea',
      'Marea',
      'Multipla',
      'Palio',
      'Panda',
      'Polonez',
      'Punto',
      'Regata',
      'Regatta 100S',
      'Ritmo',
      'Scudo',
      'Seicento',
      'Siena',
      'Spider Europa',
      'Stilo',
      'Strada',
      'Talento',
      'Tempra',
      'Tipo',
      'Ulysee',
      'Uno',
      'X 1/9',
      'Այլ/Օther',
    ],
  },
  {
    name: 'Fisker',
    children: ['Ocean One'],
  },
  {
    name: 'Ford',
    children: [
      'Aerostar',
      'Aspire',
      'Bronco',
      'Capri',
      'Cargo',
      'Contour',
      'Cougar',
      'Courier',
      'Crown Victoria',
      'Econoline',
      'Econovan',
      'Ecosport',
      'Edge',
      'Escape',
      'Escort',
      'Excursion',
      'Expedition',
      'Explorer',
      'Express',
      'F-550',
      'F150',
      'F250',
      'F350',
      'Fairlane',
      'Falcon',
      'Fiesta',
      'Flex',
      'Focus',
      'Focus C-Max',
      'Fusion',
      'Galaxy',
      'Granada',
      'GT',
      'Ka',
      'Kuga',
      'Mach-e',
      'Maverick',
      'Mercury',
      'Mondeo',
      'Mustang',
      'Orion',
      'Probe',
      'Puma',
      'Ranger',
      'S-Max',
      'Scorpio',
      'Sierra',
      'Streetka',
      'Taunus',
      'Taurus',
      'Tempo',
      'Territori EV',
      'Thunderbird',
      'Tourneo',
      'Transit',
      'Windstar',
    ],
  },
  {
    name: 'Foton',
    children: ['BJ5099', 'Forland 2007'],
  },
  {
    name: 'GAC',
    children: ['Aion S', 'Aion V'],
  },
  {
    name: 'GAZ',
    children: [
      '12',
      '14 Чайка',
      '172412',
      '20 Победа',
      '21 Волга',
      '24',
      '270710',
      '2747',
      '2775',
      '2790',
      '2818',
      '3102',
      '31029',
      '3110',
      '3110 Валдай',
      '31105',
      '3111',
      '3202',
      '320202',
      '330230',
      '330250',
      '330252',
      '33027',
      '330270',
      '3306',
      '3307',
      '33073',
      '3308 Sadko',
      '3309',
      '3310',
      '33104',
      '331041',
      '33106',
      '331061',
      '3390',
      '3507',
      '35071',
      '4301',
      '51',
      '52',
      '5201',
      '53',
      '5312',
      '63',
      '66',
      '66-15',
      '69',
      'Siber',
      'АА',
      'Баргузин',
      'ГАЗ',
      'Газель',
      'Газель Business',
      'Газель NEXT',
      'Газон-NEXT',
      'Садко',
      'Соболь',
      'Соболь 4x4',
      'Соболь Бизнес',
    ],
  },
  {
    name: 'Geely',
    children: [
      'Atlas',
      'CK',
      'Coolray',
      'Emgrand',
      'EX5',
      'FC',
      'Galaxy E5',
      'Galaxy E8',
      'Geome',
      'Geometery E',
      'Geometry A',
      'Geometry C',
      'HQ',
      'M305',
      'M6',
      'MK',
      'Monjaro',
      'Tugella',
      'Yuancheng E6 VAN',
      'Yuancheng F1E',
      'Yuancheng V6',
    ],
  },
  {
    name: 'Genesis',
    children: [
      'G70',
      'G70 Shooting brake',
      'G80',
      'G80 Electrified',
      'G90',
      'GV60',
      'GV70',
      'GV70 Electrified',
      'GV80',
    ],
  },
  {
    name: 'GMC',
    children: [
      'Acadia',
      'Canyon',
      'Envoy',
      'Hummer',
      'Hummer EV',
      'Jimmy',
      'Safary',
      'Savana',
      'Sierra',
      'Sonoma',
      'Suburban',
      'Syclone',
      'Terrain',
      'Treker',
      'Typhoon',
      'Vandura',
      'Yukon',
    ],
  },
  {
    name: 'GWM',
    children: [
      'GWM UTE',
      'Haval H6',
      'Haval H6 GT',
      'Haval Julion',
      'Ora',
      'Poer',
      'Tank 300',
      'Tank 500',
      'Tank 700',
    ],
  },
  {
    name: 'Haval',
    children: ['F7x'],
  },
  {
    name: 'Honda',
    children: [
      'Accord',
      'Activa 125',
      'Aerodeck',
      'Africa Twin',
      'Africa Twin 1100',
      'Africa Twin CRF 1000 L',
      'Airwave',
      'Ascot',
      'Avancier',
      'Ballada',
      'Beat',
      'Capa',
      'CB',
      'CBF',
      'CBR',
      'CBX',
      'City',
      'Civic',
      'Clarity',
      'Concerto',
      'CR-V',
      'CR-Z',
      'CRF',
      'CRM',
      'Crosstour',
      'CRX',
      'Del Sol',
      'DN-01',
      'Domani',
      'e:NP1',
      'e:NP2',
      'e:NS1',
      'ED 9',
      'Edix',
      'Element',
      'Elysion',
      'Fit',
      'FR-V',
      'Freed',
      'GB',
      'GL1800A Gold Wing',
      'Goldwing',
      'Goldwing Tour',
      'Horizon',
      'Hornet',
      'Hornet 2.0',
      'HR-V',
      'Insight',
      'Inspire',
      'Integra',
      'Jazz',
      'Lagreat',
      'Legend',
      'Life',
      'Logo',
      'M-NV',
      'Magna',
      'MDX',
      'Mobilio',
      'Navi Scooter',
      'NC 750 X',
      'NC700',
      'NSR',
      'NSX',
      'Odyssey',
      'Orthia',
      'Partner',
      'Passport',
      'Pilot',
      'Prelude',
      'Rafaga',
      'Rebel',
      'Rebel CMX 1100 Touring Pack',
      'Rebel CMX 500 A',
      'Ridgeline',
      'S 2000',
      'S-MX',
      'Saber',
      'Shadow',
      'Shuttle',
      'Silver Wing',
      'Spike',
      'ST1300A Pan-European',
      'Steed',
      'Stepwgn',
      'Strea M',
      'Stream',
      'Today',
      'Torneo',
      'TRX',
      'Vamos',
      'VF',
      'VFR',
      'VFR800X Crossrunner',
      'Vigor',
      'VT1300CX',
      'VTX1800',
      'XL1000VA Varadero',
      'XL700VA Transalp',
      'XLR',
      'XR',
      'Z',
    ],
  },
  {
    name: 'Hongqi',
    children: ['E-HS9', 'E-QM5', 'EH7'],
  },
  {
    name: 'Huanghai Auto',
    children: ['Aurora'],
  },
  {
    name: 'Huawei',
    children: ['Aito M5'],
  },
  {
    name: 'Hummer',
    children: ['H1', 'H2', 'H3'],
  },
  {
    name: 'IM Motors',
    children: ['L 7', 'LS 6', 'LS 7'],
  },
  {
    name: 'Ineos',
    children: ['Grenadier'],
  },
  {
    name: 'Infiniti',
    children: [
      'EX35',
      'EX37',
      'FX35',
      'FX37',
      'FX45',
      'FX50',
      'G20',
      'G25',
      'G35',
      'G37',
      'G45',
      'I30',
      'I35',
      'J30',
      'JX35',
      'M25',
      'M35',
      'M37 Sport',
      'M45',
      'Q35',
      'Q40',
      'Q45',
      'Q50',
      'Q60',
      'Q70',
      'QX30',
      'QX4',
      'QX50',
      'QX55',
      'QX56',
      'QX60',
      'QX70',
      'QX80',
      'XVL',
    ],
  },
  {
    name: 'Iran Khodro',
    children: [
      'Dena',
      'Pars',
      'Paykan',
      'Paykan Pick Up 1600',
      'Peugeot RD',
      'Runna',
      'Sahra',
      'Samand',
      'Sarir',
      'Soren',
    ],
  },
  {
    name: 'Isuzu',
    children: [
      'Amigo',
      'Ascender',
      'Aska',
      'Axiom',
      'Bighorn',
      'D-Max',
      'Elf',
      'Fargo',
      'Filly',
      'Forward',
      'Gemini',
      'Giga',
      'Hombre',
      'Impulse',
      'Midi',
      'MU-X',
      'NKR',
      'NPR',
      'NQR',
      'Oasis',
      'Pa Nero',
      'Rodeo',
      'TFR 10',
      'TFR 16',
      'TFR 17',
      'TFR 54',
      'TFS 16',
      'TFS 17',
      'TFS 54',
      'Trooper',
      'V330',
      'V340',
      'Vehi Cross',
      'Wizard',
    ],
  },
  {
    name: 'IZH',
    children: ['2125', '2126', '2715', '2717', '434', 'Fabula', 'Ника'],
  },
  {
    name: 'JAC',
    children: [
      'A60',
      'e-JS4',
      'iEV7S',
      'J7',
      'JS6',
      'K7',
      'M3',
      'M4',
      'M6',
      'N120',
      'N200',
      'N350',
      'N56',
      'N80',
      'S3',
      'S4',
      'S5',
      'S7',
      'Sunray Cargo V4',
      'Sunray Cargo V6',
      'T6',
      'T8',
      'T8 Pro',
      'T9',
      'V4',
      'V6',
      'X100',
      'X200',
    ],
  },
  {
    name: 'Jaguar',
    children: [
      'Daimler',
      'E-Pace',
      'E-Type',
      'F-Pace',
      'F-Type',
      'I-Pace',
      'Mk II',
      'S-Type',
      'Sovereign',
      'X-Type',
      'XE',
      'XF',
      'XJ',
      'XJ12',
      'XJ40',
      'XJ6',
      'XJ8',
      'XJR',
      'XJS',
      'XJSC Convertible',
      'XK8',
      'XK9',
      'XKR',
    ],
  },
  {
    name: 'Jeep',
    children: [
      'Cherokee',
      'CJ',
      'Comanche',
      'Commander',
      'Compass',
      'Gladiator',
      'Grand Cherokee',
      'Liberty',
      'Patriot',
      'Renegade',
      'Wagoner',
      'Willys',
      'Wrangler',
    ],
  },
  {
    name: 'Jetour',
    children: ['Dashing', 'X70', 'X70 PLUS', 'X90', 'X90 PLUS', 'X95'],
  },
  {
    name: 'Jmev',
    children: ['Elight', 'EV2', 'EV3'],
  },
  {
    name: 'Karry',
    children: ['Cowfish', 'Dolphin', 'Elephant'],
  },
  {
    name: 'Kia',
    children: [
      'Avella',
      'Besta',
      'Borrego',
      'Cadenza',
      'Capital',
      'Carens',
      'Carnival',
      'Ceed',
      'Cerato',
      'Clarus',
      'Elan',
      'Enterprise',
      'EV5',
      'EV6',
      'EV9',
      'Forte',
      'Forte Coupe',
      'Grand Bird',
      'Joice',
      'K2500',
      'K2700',
      'K3 EV',
      'K4',
      'K5',
      'K7',
      'K900',
      'Kosmos',
      'Leo',
      'Magentis',
      'Mentor',
      'Mohave',
      'Niro',
      'Opirus',
      'Optima',
      'Picanto',
      'Potentia',
      'Pregio',
      'Pride',
      'Quoris',
      'Retona',
      'Rexton',
      'Rio',
      'Roadster',
      'Rocsta',
      'Sedona',
      'Seltos',
      'Sephia',
      'Shuma',
      'Sorento',
      'Soul',
      'Soul EV',
      'Spectra',
      'Sportage',
      'Stinger',
      'Telluride',
      'Trajet',
      'Venga',
      'Visto',
    ],
  },
  {
    name: 'Lamborghini',
    children: [
      'Aventador',
      'Cheetah',
      'Countach',
      'Diablo',
      'Espada',
      'Gallardo',
      'Huracan',
      'Jalpa',
      'Jarama',
      'LM',
      'Miura',
      'Murcielago',
      'Revuelto',
      'Urraco',
      'Urus',
    ],
  },
  {
    name: 'Lancia',
    children: [
      'Beta',
      'Dedra',
      'Delta',
      'Flaminia',
      'Fulvia',
      'Gamma',
      'Integral',
      'Kappa',
      'Lybra',
      'Musa',
      'Phedra',
      'Prisma',
      'Stratos',
      'Thema',
      'Thesis',
      'Y',
      'Y Elefantio',
      'Ypsilon',
      'Zeta',
    ],
  },
  {
    name: 'Land Rover',
    children: [
      'Defender',
      'Discovery',
      'Discovery Sport',
      'Freelander',
      'Range Rover',
      'Range Rover Evoque',
      'Range Rover Sport',
      'Range Rover Velar',
    ],
  },
  {
    name: 'Leapmotor',
    children: ['C01', 'C11', 'S01', 'T03'],
  },
  {
    name: 'Lexus',
    children: [
      'CT Series',
      'CT200h',
      'ES Series',
      'ES 200',
      'ES 250',
      'ES 300',
      'ES 330',
      'ES 350',
      'GS Series',
      'GS 300',
      'GS 350',
      'GS 350 F Sport',
      'GS 400',
      'GS 430',
      'GS 450h',
      'GS 450h F Sport',
      'GS F',
      'GS Turbo',
      'GS Turbo F Sport',
      'GX Series',
      'GX 460',
      'GX 460 Luxary',
      'GX 460 Premium',
      'GX 470',
      'GX 550',
      'HS 250',
      'IS Series',
      'ES 300h',
      'IS 200',
      'IS 220',
      'IS 250',
      'IS 300',
      'IS 300 F Sport',
      'IS 350',
      'IS 350 F Sport',
      'IS Turbo',
      'IS Turbo F Sport',
      'LC Series',
      'LC 500',
      'LC 500h',
      'LM Series',
      'LM 350h',
      'LM 500h',
      'LS Series',
      'LS 300',
      'LS 400',
      'LS 430',
      'LS 460',
      'LS 460 AWD',
      'LS 460 F SPORT',
      'LS 460 L',
      'LS 460 L AWD',
      'LS 470',
      'LS 500',
      'LS 600h',
      'LX Series',
      'LX 430',
      'LX 450',
      'LX 450d',
      'LX 470',
      'LX 500d',
      'LX 570',
      'LX 600',
      'NX Series',
      'NX 200',
      'NX 200t',
      'NX 300h',
      'NX 300t',
      'NX 350',
      'NX Turbo',
      'NX Turbo F Sport',
      'RC Series',
      'RC 200t',
      'RC 300',
      'RC 350',
      'RC F',
      'RC Turbo',
      'RC Turbo F Ssport',
      'RX Series',
      'RX 200t',
      'RX 270',
      'RX 300',
      'RX 330',
      'RX 350',
      'RX 350 F Sport',
      'RX 400h',
      'RX 450h',
      'RX 450h F Sport',
      'RX 500h',
      'RZ Series',
      'RZ 450e',
      'SC Series',
      'SC 300',
      'SC 400',
      'SC 430',
      'TX',
      'UX 200',
      'UX 300e',
    ],
  },
  {
    name: 'Lifan',
    children: ['Solano', 'X50'],
  },
  {
    name: 'Lincoln',
    children: [
      'Aviator',
      'Continental',
      'LS',
      'Mark',
      'Mark LT',
      'Mark VIII',
      'MKC',
      'MKT',
      'MKX',
      'MKZ',
      'Navigator',
      'Towncar',
    ],
  },
  {
    name: 'Lixiang',
    children: ['Li L6', 'Li L7', 'Li L8', 'Li L9', 'Li MEGA'],
  },
  {
    name: 'Lotus',
    children: [
      'Elan',
      'Eletre',
      'Elise',
      'Elite',
      'Emeya',
      'Esprit',
      'Europa',
      'Excel',
      'Exige',
      'Nyo Eletre',
      'Super Seven',
      'V8',
    ],
  },
  {
    name: 'LuAZ',
    children: ['969'],
  },
  {
    name: 'Lucid',
    children: ['Air'],
  },
  {
    name: 'Luxgen',
    children: ['7 MPV', '7 SUV', 'S3', 'S5', 'U5', 'U6', 'U7 Turbo'],
  },
  {
    name: 'Mahindra',
    children: [
      'Armada',
      'Bolero',
      'Commander',
      'Defence System',
      'Double Cab',
      'MM',
      'Pik Up',
      'Scorpio',
      'Single Cab',
      'Voyager',
    ],
  },
  {
    name: 'Maserati',
    children: [
      '222',
      '224',
      '228',
      '3200',
      '418',
      '420',
      '4200',
      '422',
      '424',
      '430',
      'Biturbo',
      'Coupe Cambiocorsa',
      'Ghibli',
      'GranCabrio',
      'Gransport',
      'GranTurismo',
      'Indy',
      'Karif',
      'Levante',
      'MC12',
      'Merak',
      'Quattroporte',
      'Shamal',
      'Spyder',
    ],
  },
  {
    name: 'Maxus',
    children: ['EV80'],
  },
  {
    name: 'Maybach',
    children: ['57', '57S', '62'],
  },
  {
    name: 'Mazda',
    children: [
      '121',
      '2',
      '3',
      '323',
      '5',
      '6',
      '626',
      '929',
      'Atenza',
      'Axela',
      'Az-wagon',
      'B Series',
      'B-Fighter',
      'B2000',
      'B2500',
      'Bongo',
      'Business',
      'Capella',
      'Carol',
      'CX 30',
      'CX 50',
      'CX 90',
      'CX3',
      'CX5',
      'CX7',
      'CX9',
      'Demio',
      'E Series',
      'Efini MS-8',
      'Eunos',
      'EZ-6',
      'Famillia',
      'Luci',
      'Millenia',
      'MPV',
      'MX-3',
      'MX-30 EV',
      'MX-5',
      'MX-6',
      'Navajo',
      'Premacy',
      'Proceed',
      'Protege',
      'Roadster',
      'RX-6',
      'RX-7',
      'RX-8',
      'Tribute',
      'Verisa',
      'Xedos 6',
      'Xedos 9',
    ],
  },
  {
    name: 'McLaren',
    children: ['570s'],
  },
  {
    name: 'Mercury',
    children: ['Cougar', 'Grand Marquis', 'Mountaineer', 'Mystique', 'Sable', 'Topaz', 'Villager'],
  },
  {
    name: 'MG',
    children: ['Cyberster', 'MGA', 'MGB', 'MGF', 'Midget', 'Montego', 'TD', 'TF', 'ZR', 'ZS', 'ZT'],
  },
  {
    name: 'Mini',
    children: [
      '1000',
      '1300',
      'Clubman',
      'Convertible',
      'Cooper',
      'Cooper S',
      'Countryman',
      'Countryman Park lane',
      'John Cooper Works',
      'ONE',
      'Paceman',
    ],
  },
  {
    name: 'Mitsubishi',
    children: [
      '3000 GT',
      'Airtrek',
      'Aspire',
      'ASX',
      'Canter',
      'Carisma',
      'Cedia',
      'Challenger',
      'Chariot',
      'Colt',
      'Cordia',
      'Cosmos',
      'Delica',
      'Diamante',
      'Dingo',
      'Dion',
      'Eclipse',
      'Eclipse Cross',
      'Endeavor',
      'Expo',
      'Externa',
      'FD',
      'FG',
      'FTO',
      'Fuso',
      'Fuso Rosa',
      'FV',
      'Galant',
      'Grandis',
      'GTO',
      'L200',
      'L300',
      'L400',
      'Lancer',
      'Legnum',
      'Libero',
      'Magna',
      'Minicab',
      'Mirage',
      'Montero',
      'Montero Sport',
      'Nativa',
      'Outlander',
      'Outlander PHEV',
      'Pajero',
      'Pajero Mini',
      'Pajero Pinin (IO)',
      'Rosa',
      'RVR',
      'Santamo',
      'Sapporo',
      'Sigma',
      'Space Gear',
      'Space Runner',
      'Space Star',
      'Space Wagon',
      'SPB',
      'Starion',
      'Toppo',
      'Town Box',
      'Tredia',
      'Xpander',
      'Օutlander Sport',
    ],
  },
  {
    name: 'Mitsuoka',
    children: ['Galue', 'Himiko', 'Ryugi', 'Viewt'],
  },
  {
    name: 'Moskvich',
    children: ['2140', '2141', 'Князь-Владимир', 'Святогор', 'Юрий Долгорукий'],
  },
  {
    name: 'Neta',
    children: ['AYA', 'GT', 'L', 'S', 'U 400', 'U 500', 'U 500 Pro', 'U 610', 'V Pro', 'X'],
  },
  {
    name: 'Nio',
    children: ['EL6', 'EL8', 'ES6', 'ES8', 'ET5', 'ET7', 'ET9'],
  },
  {
    name: 'OKA',
    children: ['1111', '11113', '11301'],
  },
  {
    name: 'Oldsmobile',
    children: [
      'Achieva',
      'Alero',
      'Aurora',
      'Bravada',
      'Calais',
      'Custom Cruiser',
      'Cutlass Supreme',
      'Delta 88',
      'Omega',
      'Silhouette',
      'Tornado',
    ],
  },
  {
    name: 'Onvo',
    children: ['L60', 'L90'],
  },
  {
    name: 'Opel',
    children: [
      'Agila',
      'Antara',
      'Arena',
      'Ascona',
      'Astra',
      'Calibra',
      'Cavalier',
      'Combo',
      'Commodore',
      'Corsa',
      'Crossland',
      'Diplomat',
      'Frontera',
      'Grandland',
      'GT',
      'Insignia‎',
      'Kadett',
      'Manta',
      'Meriva',
      'Mokka',
      'Monterey',
      'Monza',
      'Movano',
      'Nova',
      'Omega',
      'Pick Up Sportscap',
      'Rekord',
      'Senator',
      'Signum',
      'Sintra',
      'Speedster',
      'Tigra',
      'Vectra',
      'Vectra B',
      'Vita',
      'Vivaro',
      'Zafira',
    ],
  },
  {
    name: 'Peugeot',
    children: [
      '1007',
      '104',
      '106',
      '107',
      '2008',
      '204',
      '205',
      '206',
      '207',
      '208',
      '3008',
      '301',
      '304',
      '305',
      '306',
      '307',
      '308',
      '309',
      '4007',
      '404',
      '405',
      '406',
      '407',
      '408',
      '504',
      '505',
      '508',
      '604',
      '605',
      '607',
      '806',
      '807',
      'Bipper',
      'Boxer',
      'e-2008',
      'Expert',
      'J5',
      'Partner',
      'Partner Tepee',
      'RCZ',
    ],
  },
  {
    name: 'Plymouth',
    children: ['Breeze', 'Grand Voyager', 'Neon', 'Prowler', 'Voyager'],
  },
  {
    name: 'Polar',
    children: ['Stone 01'],
  },
  {
    name: 'Polestar',
    children: ['1', '2', '3'],
  },
  {
    name: 'Pontiac',
    children: [
      '6000',
      'Bonneville',
      'Fiero',
      'FireBird',
      'G6',
      'Grand Am',
      'Grand Prix',
      'GTO',
      'Montana',
      'Solstice Roadster',
      'Sunbird',
      'Sunfire',
      'Targa',
      'Trans Am',
      'Trans Sport',
      'Vibe',
    ],
  },
  {
    name: 'Porsche',
    children: [
      '356',
      '718',
      '911',
      '912',
      '914',
      '924',
      '928',
      '944',
      '959',
      '962',
      '968',
      'Boxster',
      'Carrera GT',
      'Cayenne',
      'Cayenne Coupe',
      'Cayman',
      'Macan',
      'Panamera',
      'Taycan',
    ],
  },
  {
    name: 'Qiyuan',
    children: ['A07'],
  },
  {
    name: 'RAF',
    children: ['2203'],
  },
  {
    name: 'Ram',
    children: ['1500', '2500', '3500'],
  },
  {
    name: 'Renault',
    children: [
      'Alpine A110',
      'Alpine A310',
      'Alpine V6',
      'Arkana',
      'Avantime',
      'Captur',
      'Cerax',
      'Clio',
      'Coupe',
      'Dokker',
      'Duster',
      'Espace',
      'Express',
      'Fluence',
      'Fuego',
      'Grand Espace',
      'Grand Scenic',
      'Kangoo',
      'Kaptur',
      'Koleos',
      'Laguna',
      'Logan',
      'Logan MCV',
      'Logan Van',
      'Magnum',
      'Mascott',
      'Master',
      'Megane',
      'Modus',
      'P 1400',
      'R 11',
      'R 14',
      'R 17',
      'R 18',
      'R 19',
      'R 21',
      'R 25',
      'R 30',
      'R 4',
      'R 5',
      'R 6',
      'R 9',
      'Rapid',
      'S150',
      'Safrane',
      'Sandero',
      'Sandero Stepway',
      'Scenic',
      'Spider',
      'Symbol',
      'T-Series',
      'Talisman',
      'Trafic',
      'Twingo',
      'Twizy',
      'Vel Satis',
      'Zoe',
    ],
  },
  {
    name: 'Riddara',
    children: ['RD6'],
  },
  {
    name: 'Rivian',
    children: ['R1S', 'R1T'],
  },
  {
    name: 'Rolls Royce',
    children: [
      'Corniche',
      'Cullinan',
      'Dawn',
      'Flying Spur',
      'Ghost',
      'Park Ward',
      'Phantom',
      'Silver Cloud',
      'Silver Dawn',
      'Silver Seraph',
      'Silver Shadow',
      'Silver Spirit',
      'Silver Spur',
      'Spectre',
      'Wraith',
    ],
  },
  {
    name: 'Rover',
    children: [
      '100',
      '111',
      '114',
      '115',
      '200',
      '213',
      '214',
      '216',
      '218',
      '220',
      '25',
      '400',
      '414',
      '416',
      '418',
      '420',
      '45',
      '600',
      '618',
      '620',
      '623',
      '75',
      '800',
      '820',
      '825',
      '827',
      'City Rover',
      'Maestro',
      'Metro',
      'MGH',
      'Montego',
      'SD',
      'Shotgun 650',
      'Street Wise',
    ],
  },
  {
    name: 'Ruichi',
    children: [
      'CHENGLONG BEV L2',
      'EC31 Cargo Box (PVC)',
      'EC31 L',
      'EC31 S',
      'EC35 II',
      'EC35 V',
      'EC71 L',
      'EC71 L Cargo Box',
      'EC72',
      'EC75 EV Cargo Box',
      'ED71',
      'ED71 Cargo Box',
      'EG71',
      'ES50',
    ],
  },
  {
    name: 'Saab',
    children: ['9-3', '9-5', '9-7X', '90', '900', '9000', '96', '99'],
  },
  {
    name: 'Samsung',
    children: ['SM 520', 'Այլ/Օther'],
  },
  {
    name: 'Saturn',
    children: ['Aura', 'Ion Quad Coupe', 'Ion Sedan', 'Relay', 'Sky', 'SL', 'SL1', 'VUE'],
  },
  {
    name: 'Scion',
    children: ['tC', 'xA', 'xB'],
  },
  {
    name: 'Seat',
    children: [
      'Alhambra',
      'Altea',
      'Arosa',
      'Cordoba',
      'Ibiza',
      'Inca',
      'Leon',
      'Malaga',
      'Marbella',
      'Terra',
      'Toledo',
    ],
  },
  {
    name: 'Sena',
    children: ['E400'],
  },
  {
    name: 'SG',
    children: ['DG1020', 'DG6400', 'DG6471B', 'DG6472', 'DG6480', 'G1020', 'HuangHai'],
  },
  {
    name: 'Shenlan',
    children: ['S7'],
  },
  {
    name: 'Skoda',
    children: [
      '105',
      '120',
      '130',
      '135',
      'Fabia',
      'Favorit',
      'Felicia',
      'Forman',
      'Kodiaq',
      'Octavia',
      'Octavia II',
      'Rapid',
      'Roomster',
      'SuberB',
      'Yeti',
    ],
  },
  {
    name: 'Skywell',
    children: ['BE11', 'ET 5'],
  },
  {
    name: 'Smart',
    children: ['CrossBlade', 'ForFour', 'ForTwo', 'Roadster'],
  },
  {
    name: 'SsangYong',
    children: [
      'Actyon',
      'Chairman',
      'Family',
      'Istana',
      'Korando',
      'Kyron',
      'Musso',
      'Rexton',
      'Rodius',
      'Tivoli',
      'XLV',
    ],
  },
  {
    name: 'Subaru',
    children: [
      'Ascent',
      'Baja',
      'BRZ',
      'Domingo',
      'E12',
      'Exiga',
      'Forester',
      'Impreza',
      'Justy',
      'Legacy',
      'Leone',
      'Libero',
      'Outback',
      'Pleo',
      'R1',
      'R2',
      'Sambar',
      'Solterra',
      'Stella',
      'SVX',
      'Traviq',
      'Tribeca',
      'Vivio',
      'WRX',
      'XT',
      'XV Crosstrek',
    ],
  },
  {
    name: 'Suzuki',
    children: [
      'Aerio',
      'Alto',
      'Baleno',
      'Bandit',
      'Boulevard',
      'Cappuccino',
      'Carry',
      'Celerio',
      'Cultus',
      'Desperado',
      'DR',
      'Escudo',
      'Esteem',
      'Every',
      'GN',
      'Grand Vitara',
      'GS',
      'GSF',
      'GSR',
      'GSX',
      'GT',
      'Hayabusa',
      'Hustler',
      'Ignis',
      'Intruder',
      'Jimny',
      'Kei',
      'Kizashi',
      'Liana',
      'LJ',
      'S-Cross',
      'Samurai',
      'Sidekick',
      'SJ',
      'Splash',
      'Super Carry',
      'Swift',
      'SX 4',
      'Vitara',
      'Wagon R+',
      'X-90',
      'XL-7',
    ],
  },
  {
    name: 'Tagaz',
    children: ['Aquila', 'Vega'],
  },
  {
    name: 'Tesla',
    children: ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y'],
  },
  {
    name: 'Triumph',
    children: ['TR3A'],
  },
  {
    name: 'UAZ',
    children: [
      '22069',
      '23602',
      '31519 Hunter',
      '3153',
      '3159 Барс',
      '3160',
      '31622 Simbir',
      '3163 Patriot',
      '3303',
      '3741',
      '39094',
      '39099',
      '3962',
      '469',
      'Profi',
    ],
  },
  {
    name: 'VAZ (Lada)',
    children: [
      '2101',
      '21013',
      '2102',
      '2103',
      '2104',
      '2105',
      '2106',
      '2107',
      '2108',
      '2109',
      '21099',
      '2110',
      '2111',
      '2112',
      '2113',
      '2114',
      '2115',
      '2120',
      '2121 NIVA (4x4)',
      '2123',
      '2131 NIVA (4x4)',
      '2170 Priora',
      '2172 Priora',
      '2329',
      'Granta',
      'Kalina',
      'Largus',
      'NIVA Legend',
      'NIVA Off-Road',
      'NIVA Travel',
      'Vesta',
      'XRAY',
    ],
  },
  {
    name: 'Volkswagen',
    children: [
      '181',
      'Amarok',
      'Arteon',
      'Atlas',
      'Bora',
      'Buggy',
      'Caddy',
      'California',
      'Caravelle',
      'Corrado',
      'Crafter',
      'e-Bora',
      'E-Golf',
      'e-Lavida',
      'e-Tharu',
      'EOS',
      'FOX',
      'Golf',
      'ID.3',
      'ID.4',
      'ID.5',
      'iD.6',
      'iD.7',
      'Iltis',
      'Jetta',
      'Kafer Beetle',
      'Karmann Ghia',
      'LT',
      'Lupo',
      'Multivan',
      'New Beetle',
      'Passat',
      'Passat CC',
      'Phaeton',
      'Pointer',
      'Polo',
      'Routan',
      'Santana',
      'Scirocco',
      'Sharan',
      'Shuttle',
      'Taos',
      'Taro',
      'Tiguan',
      'Touareg',
      'Touran',
      'Transporter',
      'Vento',
    ],
  },
  {
    name: 'Volvo',
    children: [
      '240',
      '244',
      '245',
      '262',
      '264',
      '265',
      '340',
      '343',
      '345',
      '360',
      '440',
      '460',
      '480',
      '740',
      '744',
      '745',
      '760',
      '780',
      '850',
      '855',
      '940',
      '944',
      '945',
      '960',
      '965',
      'C30',
      'C40',
      'C70',
      'F',
      'FE',
      'FH',
      'FL',
      'FL7',
      'FLC',
      'FM',
      'FMX',
      'FS',
      'Polar',
      'S40',
      'S60',
      'S70',
      'S80',
      'S90',
      'T5',
      'V40',
      'V50',
      'V60',
      'V70',
      'V90',
      'VHD',
      'VM',
      'VN',
      'VNL',
      'VNM',
      'VT',
      'XC40',
      'XC60',
      'XC70',
      'XC90',
    ],
  },
  {
    name: 'Voyah',
    children: ['Chasing Light', 'Courage', 'Dream', 'Dreamer', 'Free', 'PASSION'],
  },
  {
    name: 'Weltmeister',
    children: ['EX5'],
  },
  {
    name: 'Wuling',
    children: [
      'G100 Cargo Van',
      'G100P Cargo Box',
      'G100P Mini Truck',
      'G100P Refrigerator',
      'G101 Passenger',
      'Golf Car',
      'Hongguang EV',
      'Yangguang EV',
    ],
  },
  {
    name: 'Xiaomi',
    children: ['SU7'],
  },
  {
    name: 'Xpeng',
    children: ['G31', 'G3i', 'G6', 'G9', 'P5', 'P7', 'X9'],
  },
  {
    name: 'ZAZ-Tavria',
    children: ['1102', '1105', '965', '966', '968M', 'Sens', 'Славута', 'Таврия'],
  },
  {
    name: 'Zeekr',
    children: ['001', '007', '009', '7X', 'X'],
  },
  {
    name: 'Zx Auto',
    children: ['Admiral Landmark', 'Admiral Pickup', 'Admiral SUV'],
  },
];
